'use strict';
const menuButton=document.querySelector('.site-menu-button');
const menu=document.querySelector('.site-links');
function closeMenu(){if(!menuButton||!menu)return;menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Abrir menu');}
if(menuButton&&menu){menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open')){closeMenu();menuButton.focus();}});document.addEventListener('click',e=>{if(!menu.contains(e.target)&&!menuButton.contains(e.target))closeMenu();});window.matchMedia('(min-width:851px)').addEventListener('change',e=>{if(e.matches)closeMenu();});}
const filters=[...document.querySelectorAll('.gallery-filters button')];
const albums=[...document.querySelectorAll('.gallery-card')];
filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let shown=0;albums.forEach(album=>{const visible=button.dataset.category==='all'||album.dataset.category===button.dataset.category;album.hidden=!visible;if(visible)shown++;});const empty=document.querySelector('.gallery-no-results');if(empty)empty.hidden=shown!==0;}));
const dialog=document.querySelector('.photo-dialog');
if(dialog){let trigger;const image=dialog.querySelector('img');document.querySelectorAll('.photo-button').forEach(button=>button.addEventListener('click',()=>{trigger=button;image.src=button.dataset.src;image.alt=button.dataset.alt;dialog.querySelector('p').textContent=button.dataset.caption;dialog.showModal();}));dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(trigger)trigger.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});}
const tabs=[...document.querySelectorAll('.portfolio-tab')];
function selectTab(index,focus){tabs.forEach((tab,i)=>{const selected=i===index;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;document.getElementById(tab.getAttribute('aria-controls')).hidden=!selected;});if(focus)tabs[index].focus();}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectTab(index,false));tab.addEventListener('keydown',e=>{let next=-1;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==-1){e.preventDefault();selectTab(next,true);}});});
